export const ADMIN = 'АДМИН';
export const OWNER = 'ВЛАДЕЛЕЦ';
export const RAFFLE = 'РОЗЫГРЫША';
export const Change_Widget = 'Изменить виджет';
export const ADMIN_Nested = 'АДМИНИСТРАТОР';
export const FOLOWERS_Nested = 'ПОДПИСЧИКОВ';
export const ERROR_Nested = 'ERROR';
export const Raffle_Id = ' Розыгрыш №';
export const Change_CarouselCard = 'Изменено:'